services:
  - docker

before_install:
  - docker build -t learndocker -f Dockerfile.dev .

script:
  - docker run -e CI=true learndocker npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
  region: "us-east-2"
  app: "hello-docker"
  env: "Hellodocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-675572134462"
  bucket_path: "hello-docker"
  on:
    branch: main