services:
  - docker

before_install:
  - docker build -t learndocker -f Dockerfile.dev .

script:
  - docker run learndocker

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
  region: "us-east-2"
  app: "learn-docker"
  env: "Learndocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-675572134462"
  bucket_path: "learn-docker-bucket"
  on:
    branch: master