version: "3"
services: 
  dev: 
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - 3000:3000
    volumes:
      - /var/app/node_modules
      - .:/var/app
  test:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /var/app/node_modules
      - .:/var/app
    command: ["npm", "run", "test"]